name: stateful_props

version: 0.0.1+3
description: Encapsulate behavior easily across Widgets. Increase readability by reducing nesting and code locality.
author: shawn@gskinner.com
homepage: https://github.com/gskinnerTeam/flutter-stateful-props

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
